language: node_js
node_js:
  - 9
install:
  - npm install
  - npm i -g wt-cli
  - wt init --url WT_URL --container WT_CONTAINER --token WT_TOKEN
script:
  - npm run lint
  - npm run style
  - npm run build
  - npm test
after_success:
  - npm run deploy
